stages:
  - build
  - test
  - deploy
  # - other stages

variables:
  # Define global variables here
  VARIABLE: 'value'

build_job:
  stage: build
  script:
    - echo "Building"
    # Add build instructions here

test_job:
  stage: test
  script:
    - echo "Testing"
    # Add test instructions here

deploy_job:
  stage: deploy
  script:
    - echo "Deploying"
    # Add deploy instructions here
  rules:
    # Set job launch as manual
    - when: manual
      # Failure is disallowed
      allow_failure: false
